redis-sample:
  container_name: redis
  image: redis
  ports:
    - "6370:6379"

app-redis:
  container_name: spring-boot-redis
  dockerfile: docker/Dockerfile
  build: .
  restart: always
  ports:
    - "8088:8080"
  links:
    - redis-sample
  environment:
    - SPRING_PROFILES_ACTIVE=default
